# 1. Config de conexão com o banco de dados

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-rapid-thunder-acms7rmv-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DB_NAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_umiBRF1Wsg9H}

# 2. Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Configurações do hibernate (JPA)
# update cria a tabela automaticamente se ela não existir, mas não remove ou altera as tabelas existentes
spring.jpa.hibernate.ddl-auto=update
# exibir as consultas SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Configurações da porta do servidor web
server.port=8080



#spring.application.name=senaihub
